### ISSUE TITLE
"A valid Java SDK path is required in Editor Settings", editor settings are not being read

### ISSUE THREAD

**Issue by NetSysFire** [abarichello/godot-ci#151]
All builds (linux, mac and windows) export well (thanks for your work on this project!), except Android, which fails with the error in the title. I thought this was going to be an easy fix and did the following, as the value is also missing from your dockerfile:

```bash
echo 'export/android/java_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64"' >> ~/.config/godot/editor_settings-4.tres
```

But it still complained about the same error. I tried different editor settings paths, including /root/.config/godot and copying `editor_settings-4.tres` to `editor_settings-4.3.tres` (in both /root and ~/) but none worked. Then I set `JAVA_HOME` to the same value as in the config and the exporter was mostly happy. Since this environment variable is independent from the config, see the [godot source code](https://github.com/godotengine/godot/blob/master/platform/android/export/export.cpp#L52), this strongly suggests that, for whatever reason, the editor settings are not being read. 
There is no option in godot, that I found at least, to make it dump the editor settings it sees for additional debugging.

Since the `ANDROID_HOME` env var is in the dockerfile, I believe this is why it did not complain about the Android SDK path.
It also says `WARNING: Code Signing: Could not find keystore, unable to export.`, indicating again that the editor settings are not being applied.
`$XDG_DATA_HOME` and `$XDG_DATA_CONFIG` are unset or empty.

This is on github actions. You can find the file here: https://github.com/sourceofmana/sourceofmana-ci-test/blob/master/.github/workflows/godot-ci.yml
But for the sake of of saving you a click, here is a tidied up version which has some of my debug attempts removed:

```yaml
name: "godot-ci export"
on:
  push:
    branches:
    - master

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: "Source of Mana"
  PROJECT_PATH: "."

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      timestamp: ${{ steps.get-timestamp.outputs.time }}
    steps:
      - name: Get build timestamp
        id: get-timestamp
        run: |
          echo "time=$(/bin/date -u "+%Y-%m-%d-%H%M")" >> $GITHUB_OUTPUT
      - name: Get env vars
        id: generate_env_vars
        run: |
          echo "tag_name=som-experimental-"${{ steps.get-timestamp.outputs.time }} >> $GITHUB_OUTPUT
          echo "release_name=Source of Mana experimental build ${{ steps.get-timestamp.outputs.time }}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - run: gh release create ${{ steps.generate_env_vars.outputs.tag_name }} --prerelease --title "${{ steps.generate_env_vars.outputs.release_name }}" --target "$(git log -1 --format='%H')"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  builds:
    needs: release
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux
          artifact: linux
          export_template: "Linux/X11"
          ext: "x86_64"
        - name: Linux (Headless Server)
          artifact: linux-server-headless
          export_template: "Linux/X11 Headless Server"
          ext: "x86_64"
        - name: Windows
          artifact: windows
          export_template: "Windows Desktop"
          ext: "exe"
        - name: macOS
          artifact: macos
          export_template: "macOS"
          ext: "zip"
        - name: Android
          artifact: android
          export_template: "Android"
          ext: "apk"
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: barichello/godot-ci:4.3
    name: Export ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          echo 'export/android/java_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64"' >> /root/.config/godot/editor_settings-4.tres
          cp /root/.config/godot/editor_settings-4.tres /root/.config/godot/editor_settings-4.3.tres
          cp -r /root/.config/godot ~/.config/godot
          cp -r /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: ${{ matrix.name }} Build
        run: |
          mkdir -v -p "build/${{ matrix.artifact }}"
          cd "$PROJECT_PATH"
          godot --headless --verbose --export-release "${{ matrix.export_template }}" "build/${{ matrix.artifact }}/${EXPORT_NAME}-${{ matrix.artifact }}-${{ needs.release.outputs.timestamp }}.${{ matrix.ext }}"
      - name: Ensure github cli is present
        run: |
          wget https://github.com/cli/cli/releases/download/v2.55.0/gh_2.55.0_linux_amd64.deb
          dpkg -i gh_2.55.0_linux_amd64.deb
      - name: Upload artifact to release
        run: |
          git config --global --add safe.directory '*'
          gh release upload som-experimental-${{ needs.release.outputs.timestamp }} "build/${{ matrix.artifact }}/${EXPORT_NAME}-${{ matrix.artifact }}-${{ needs.release.outputs.timestamp }}.${{ matrix.ext }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by Calinou** [comment]
> `~/.config/godot/editor_settings-4.tres`

Editor settings are in `~/.config/godot/editor_settings-4.3.tres` since Godot 4.3.

**Comment by NetSysFire** [comment]
I have found the issue! Credits to paulguy for suggesting that.

You run godot and apparently this has created a dummy config in the past:

https://github.com/abarichello/godot-ci/blob/db6fb8b4f6a3b42524a6f5b775e502a25d10e5b5/Dockerfile#L59-L60

However, it does not do that anymore and it is missing the headers. I solved the issue by prepending this to the file:

```ini
[gd_resource type="EditorSettings" format=3]

[resource]
```

I'll PR that here real quick.

**Comment by Spengreb** [comment]
For me the first thing you posted actually worked when pointed to the current version: 
` echo 'export/android/java_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64"' >> ~/.config/godot/editor_settings-4.3.tres`

This is the complete debug step I have now

```
# Android Debug Job. It will use the generated debug.keystore.
android_debug:
  stage: export
  script:
    - echo 'export/android/java_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64"' >> ~/.config/godot/editor_settings-4.3.tres
    - godot --headless --verbose --export-debug "Android Debug" ./build/android/$EXPORT_NAME.apk
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/android
```

Somehow this passes

**Comment by ThunderFD** [comment]
what would be a sample job to build a test project now?
I'm trying to piece together how to get Android builds to work but no luck so far.
(I don't have any github actions experience prior to this so excuse any obvious errors)

my .yml looks something like this: (mac exporting works fine)

```yml
name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: some-name

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          echo 'export/android/java_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64"' >> /root/.config/godot/editor_settings-4.tres
          cp /root/.config/godot/editor_settings-4.tres /root/.config/godot/editor_settings-4.3.tres
          cp -r /root/.config/godot ~/.config/godot
          cp -r /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Android Build
        run: |
          mkdir -v -p build/android
          godot --headless --verbose --export-release "Android" "build/android/$EXPORT_NAME.apk"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/android

  export-mac:
    name: Mac Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot --headless --verbose --export-release "macOS" build/mac/$EXPORT_NAME.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: build/mac
```

the log looks as follows:
```
[...]
Loaded system CA certificates
EditorSettings: Save OK!
reimport: begin: (Re)Importing Assets steps: 1
	reimport: step 0: icon.svg
EditorFileSystem: Importing file: res://icon.svg
EditorFileSystem: "res://icon.svg" import took 3 ms.
reimport: end
ERROR: Cannot export project with preset "Android" due to configuration errors:
Could not find version of build tools that matches Target SDK, using 33.0.2
A valid Java SDK path is required in Editor Settings.

   at: _fs_changed (editor/editor_node.cpp:1012)
ERROR: Project export for preset "Android" failed.
   at: _fs_changed (editor/editor_node.cpp:1028)
EditorSettings: Save OK!
XR: Clearing primary interface
XR: Removed interface "Native mobile"
XR: Removed interface "OpenXR"
Orphan StringName: Start (static: 0, total: 1)
Orphan StringName: Node (static: 5, total: 6)
Orphan StringName: End (static: 0, total: 1)
StringName: 3 unclaimed string names at exit.
Error: Process completed with exit code 1.
```

**Comment by NetSysFire** [comment]
1. Wrong config file. 4.3 changed the config file name. See the linked PR.
2. All those fixes are now incorporated and are not needed anymore.

So the only thing you need to do now is copying the /root godot paths, which I also added to the sample workflow in said PR.

**Comment by NetSysFire** [comment]
I checked again. The new image has not yet been uploaded to the container registry as no changes have been applied yet. @Calinou, it looks like the workflow responsible for that was skipped. https://github.com/abarichello/godot-ci/actions/runs/11406172834/job/31739349244

**Comment by ThunderFD** [comment]
@NetSysFire oh, thanks for the follow-up! I was again trying all kinds of stuff haha.

so the sample file should just work when changing "Windows Desktop" to "Android Debug" (with an export template named that, and changing the flag to --export-debug? (I want to deal with the key for signing another day..)

Bummer that there is no sample for Android in the yml file

I'll just wait for the updated docker image then.

**Comment by NetSysFire** [comment]
In the meantime try the `echo 'export/android/java_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64"' >> ~/.config/godot/editor_settings-4.3.tres`

Make sure this runs *after* you copied /root/.config/godot or it'll create a file with missing headers.

**Comment by Calinou** [comment]
A `4.3-stable` tag was already pushed to the repository, so I don't know how I'm supposed to trigger an image upload again since I can't force-push the repository to remove the existing tag.

4.3.1 hasn't been released yet, so the tag shouldn't be called `4.3.1-stable`.

**Comment by ThunderFD** [comment]
> In the meantime try the `echo 'export/android/java_sdk_path = "/usr/lib/jvm/java-17-openjdk-amd64"' >> ~/.config/godot/editor_settings-4.3.tres`
> 
> Make sure this runs _after_ you copied /root/.config/godot or it'll create a file with missing headers.

yep, that did the trick, thanks! 

> > Bummer that there is no sample for Android in the yml file
> 
> There is one for GitLab CI, but I don't think one was ever added to the GitHub Actions workflow file. It should be straightforward to port it from GitLab CI to GitHub Actions, the main part that's different will be how you define the export secrets.

I'll probably figure that out somehow, otherwise I'll open another issue for help with that

**Comment by NetSysFire** [comment]
The manual build of the mono image fails because of
```
#16 [11/23] RUN echo '[gd_resource type="EditorSettings" format=3]' > ~/.config/godot/editor_settings-${GODOT_VERSION:0:3}.tres
#16 0.213 /bin/sh: 1: Bad substitution
```

This should not happen. However!

https://github.com/abarichello/godot-ci/blob/b87499e4bd2590c2a40d5f0c4fc5cdfc0fbc17a0/Dockerfile#L1

Ubuntu uses dash and not sh. Only with dash this issue happens. I did not introduce this error, this happened with that earlier PR, #149, which added those substitutions in the editor settings file names.
The solution for that is to enforce somehow that /bin/sh is actually /bin/sh and not /bin/dash. Or just use /bin/bash.

**Comment by Calinou** [comment]
@NetSysFire This should be fixed by https://github.com/abarichello/godot-ci/pull/158, can you check?

**Comment by NetSysFire** [comment]
For the people in this thread: This is fixed for good now. You can remove those temporary fixes, I just tested that myself.

**Comment by joanroig** [comment]
Hey @NetSysFire, I'm facing a similar issue on 4.4.1:

```
Loading resource: res://addons/gut/fonts/CourierPrime-Regular.ttf
Loading resource: res://.godot/imported/CourierPrime-Regular.ttf-3babe7e4a7a588dfc9a84c14b4f1fe23.fontdata
reimport: end
ERROR: Cannot export project with preset "Android" due to configuration errors:
A valid Java SDK path is required in Editor Settings.
Could not find version of build tools that matches Target SDK, using 33.0.2
[...]
```

My Android build action looks like this, maybe you see something missing? Thanks in advance.

```yaml
name: "godot-ci export"
on: push

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: demo
  PROJECT_PATH: demo

jobs:

  export-android:
    name: Android Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Android Build
        run: |
          mkdir -v -p build/android
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Android" "$EXPORT_DIR/android/$EXPORT_NAME.apk"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/android
```

**Comment by NetSysFire** [comment]
You have skipped the vitally important step of `mv /root/.config/godot ~/.config/godot` as per the example workflow file.

Remove those manual steps where you append to the file, it has long since been fixed and does not need manual action anymore.

**Comment by joanroig** [comment]
@NetSysFire thanks for your answer, I did not find a full example workflow file for Android in this repo, following your advice I have now copied most of the Windows steps into my Android and moved one step further:

```yaml
  export-android:
    name: Android Export
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.4.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mkdir -v -p ~/.config/
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Android Build
        run: |
          mkdir -v -p build/android
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Android" "$EXPORT_DIR/android/$EXPORT_NAME.apk"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android
          path: build/android
```
I still have a couple of build errors, but the solutions I found are about copying data to the editor_settings-4.tres, any idea how to fix this?

```
Loading resource: res://addons/gut/GutScene.tscn
Loading resource: res://addons/gut/gut_loader_the_scene.tscn
Loading resource: res://addons/gut/gut_loader_the_scene.gd
ERROR: Attempt to open script 'res://addons/gut/gut_loader_the_scene.gd' resulted in error 'File not found'.
Failed loading resource: res://addons/gut/gut_loader_the_scene.gd
   at: load_source_code (modules/gdscript/gdscript.cpp:1115)
ERROR: Failed loading resource: res://addons/gut/gut_loader_the_scene.gd. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:343)
ERROR: Cannot set object script. Parameter should be null or a reference to a valid script.
   at: set_script (core/object/object.cpp:968)
Loading resource: res://addons/gut/UserFileViewer.tscn
Loading resource: res://addons/script-ide/quickopen/quick_open_panel.tscn
Loading resource: res://objects/card.tscn
Loading resource: res://shaders/dynamic-shadow.tres
Loading resource: res://shaders/dynamic-shadow.gdshader
Loading resource: res://assets/images/cards/attack.png
Loading resource: res://.godot/imported/attack.png-e363e50c12a71d999e3005c5dd05812d.ctex
Loading resource: res://objects/card_factory.tscn
Loading resource: res://objects/card.tscn
Loading resource: res://objects/card_manager.tscn
Loading resource: res://objects/card_factory.tscn
Loading resource: res://objects/drop_zone.tscn
Loading resource: res://objects/hand.tscn
Loading resource: res://objects/pile.tscn
Loading resource: res://scenes/board.tscn
Loading resource: res://objects/card_manager.tscn
Loading resource: res://assets/images/cards-back/cardBack_blue1.png
Loading resource: res://.godot/imported/cardBack_blue1.png-7be684e30aa2d89f04b8f2eb230d1f42.ctex
Loading resource: res://objects/hand.tscn
Loading resource: res://objects/pile.tscn
Loading resource: res://assets/images/cards-back/cardBack_blue3.png
Loading resource: res://.godot/imported/cardBack_blue3.png-a762470a0b890645a255c603b7ccbfd3.ctex
Loading resource: res://assets/images/cards-back/cardBack_blue4.png
Loading resource: res://.godot/imported/cardBack_blue4.png-69bf7014dcc8c6cf67f734368b01e1b2.ctex
Loading resource: res://assets/images/cards-back/cardBack_green1.png
Loading resource: res://.godot/imported/cardBack_green1.png-fe7bc01ec6290b75a3bcc66e1086a5cc.ctex
Loading resource: res://assets/images/cards-back/cardBack_green3.png
Loading resource: res://.godot/imported/cardBack_green3.png-a79da8c7d7bcf307fb3896a0a0a18a38.ctex
Loading resource: res://assets/images/cards-back/cardBack_green4.png
Loading resource: res://.godot/imported/cardBack_green4.png-038c51f4bba260715aa89c0b3d60d9bf.ctex
Loading resource: res://shaders/dynamic-shadow.tres
Loading resource: res://shaders/shadow.tres
Loading resource: res://shaders/shadow.gdshader
	export: step 103: Aligning APK...
	export: step 104: Signing release APK...
WARNING: Code Signing: Could not find keystore, unable to export.
     at: add_message (./editor/export/editor_export_platform.h:240)
export: end
ERROR: Project export for preset "Android" failed.
   at: _fs_changed (editor/editor_node.cpp:1103)
Unloading addon: res://addons/gut/plugin.cfg
Unloading addon: res://addons/script-ide/plugin.cfg
loading_editor_layout: begin: Loading editor steps: 5
	loading_editor_layout: step 0: Loading editor layout...
loading_editor_layout: end
cannot connect to daemon at tcp:5037: Connection refused
EditorSettings: Save OK!
XR: Clearing primary interface
XR: Removed interface "Native mobile"
XR: Removed interface "OpenXR"
WARNING: 1 RID of type "Canvas" was leaked.
     at: _free_rids (servers/rendering/renderer_canvas_cull.cpp:2677)
WARNING: 75 RIDs of type "CanvasItem" were leaked.
     at: _free_rids (servers/rendering/renderer_canvas_cull.cpp:2679)
ERROR: 1 RID allocations of type 'PN13RendererDummy14TextureStorage12DummyTextureE' were leaked at exit.
ERROR: 74 RID allocations of type 'PN18TextServerAdvanced22ShapedTextDataAdvancedE' were leaked at exit.
ERROR: 3 RID allocations of type 'PN18TextServerAdvanced12FontAdvancedE' were leaked at exit.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
Leaked instance: GDScriptNativeClass:9223372043699880306
     at: cleanup (core/object/object.cpp:2378)
Leaked instance: GDScriptNativeClass:9223372043951538561
Leaked instance: StyleBoxFlat:922337206[1366](https://github.com/joanroig/demo/actions/runs/14611684928/job/40990778779#step:5:1367)289042 - Resource path: 
ERROR: Cannot get path of node as it is not in a scene tree.
Leaked instance: FontVariation:9223372057222316691 - Resource path: 
   at: get_path (scene/main/node.cpp:2345)
Leaked instance: GDScriptNativeClass:9223372048598827670
ERROR: Cannot get path of node as it is not in a scene tree.
   at: get_path (scene/main/node.cpp:2345)
ERROR: Cannot get path of node as it is not in a scene tree.
   at: get_path (scene/main/node.cpp:2345)
```

**Comment by NetSysFire** [comment]
The keystore thing is currently bugged and is a separate issue. #179
