### ISSUE TITLE
Godot 4 support?

### ISSUE THREAD

**Issue by mattkanwisher** [abarichello/godot-ci#98]
Any chance we will see GoDot 4 support soon?

**Comment by Calinou** [comment]
As I understand it, only stable releases are planned to be supported by godot-ci. As a result, Godot 4 will only be supported once 4.0 stable is released.

**Comment by realkotob** [comment]
Yes, as Calinou mentioned, we do not see value in supporting non-stable releases, as that would add unnecessary overhead to the contributors.

However I have personally made images off of betas and alphas before, so it is very possible and easy (just change the download path).

 Let me know if you have difficulty with this.

**Comment by nlaha** [comment]
Any updates? Godot 4 is stable now.
https://godotengine.org/article/godot-4-0-sets-sail/

**Comment by dmcallejo** [comment]
No headless binary for now, which is needed for this image to work afaik.

**Comment by Brawmario** [comment]
> No headless binary for now, which is needed for this image to work afaik.

There's no headless binary anymore for Godot 4. The Windows, Mac, and Linux binaries now have a headless mode that's activated when ran with the `--headless` argument.

**Comment by realkotob** [comment]
PRs welcome for anyone who wants to contribute to this 🎉

**Comment by Brawmario** [comment]
Hold on @realkotob, the current release of Godot CI 4.0 is broken! It even failed the action for the tag: https://github.com/abarichello/godot-ci/actions/runs/4309001784 . The fact is that the dedicated Linux binary is gone and needs to be adjusted in the Dockerfile, maybe PR #104 is still relevant?

**Comment by Brawmario** [comment]
I'll try to remake PR #104 later today while also updating the example workflow files.

**Comment by DavidOcacho** [comment]
Hey guys, just to confirm, this: https://hub.docker.com/r/barichello/godot-ci will be updated to the 4.0 stable as soon as the problem is fixed? Thanks!

**Comment by realkotob** [comment]
This PR has been merged so things should be fixed now
https://github.com/abarichello/godot-ci/pull/104

**Comment by Nauja** [comment]
But there is no Docker image because the action didn't run as the release tag already exists ?

**Comment by seanmaxwell** [comment]
I put together a PR for helping complete the support for Godot 4 (#105).

Hoping this can help. Let me know if there is anything I can do to help further. Thanks~

**Comment by SushiWaUmai** [comment]
Seems like there still isn't a Godot 4 image available. Any updates?

**Comment by Calinou** [comment]
See https://github.com/abarichello/godot-ci/pull/107.

It seems that not even 3.5.2 is listed on https://hub.docker.com/r/barichello/godot-ci, so I guess the automated deployment that was merged in https://github.com/abarichello/godot-ci/pull/79 isn't working. cc @TheOrioli

**Comment by TheOrioli** [comment]
The check releases is working correctly, but it seems that the current Dockerfile is incorrect, see workflow:
https://github.com/abarichello/godot-ci/actions/runs/4613295096 

To fix 3.5.2 missing, someone with maintainer access to the repository needs to run the Manual Workflow, but first the issue with the Dockerfile should be fixed.

Unfortunately, I currently do not have the capacity to take a look at it. 

What I can suggest for Godot 4 CI builds is https://github.com/chickensoft-games/setup-godot I've been using it successfully on our latest project.

**Comment by Mawdac** [comment]
> The check releases is working correctly, but it seems that the current Dockerfile is incorrect, see workflow: https://github.com/abarichello/godot-ci/actions/runs/4613295096

I believe https://github.com/abarichello/godot-ci/pull/107 has those fixes you're referring to - it was merged 2 weeks after that failed run which 404'd looking for a bad URL (the `-headless` bit in particular). Correct me if I'm wrong though

> To fix 3.5.2 missing, someone with maintainer access to the repository needs to run the Manual Workflow, but first the issue with the Dockerfile should be fixed.

I'm one of those people looking for 3.5.2 support 🥲 Anyone that could help?

**Comment by Calinou** [comment]
> I'm one of those people looking for 3.5.2 support smiling_face_with_tear Anyone that could help?

I've triggered a workflow run – check back https://github.com/abarichello/godot-ci/actions/workflows/manual_build.yml.

**Comment by TheOrioli** [comment]
> > The check releases is working correctly, but it seems that the current Dockerfile is incorrect, see workflow: https://github.com/abarichello/godot-ci/actions/runs/4613295096
> 
> I believe #107 has those fixes you're referring to - it was merged 2 weeks after that failed run which 404'd looking for a bad URL (the `-headless` bit in particular). Correct me if I'm wrong though
> 
> > To fix 3.5.2 missing, someone with maintainer access to the repository needs to run the Manual Workflow, but first the issue with the Dockerfile should be fixed.
> 
> I'm one of those people looking for 3.5.2 support 🥲 Anyone that could help?

![image](https://github.com/abarichello/godot-ci/assets/2500134/9630f33a-a6c5-4cdc-9127-c4a3114bb63b)

Seems the build worked🎊 Can you confirm your CI stuff is now operational?

**Comment by Mawdac** [comment]
Can confirm my CI stuff is "working"! (It is able to pull down and use the 3.5.2 build 🥳 but it's failing for other reasons specific to my project, might open a discussion while debugging that later 😄)

Thank you @Calinou @TheOrioli for the quick build and replies!

**Comment by Vennnot** [comment]
> What I can suggest for Godot 4 CI builds is https://github.com/chickensoft-games/setup-godot I've been using it successfully on our latest project.

Does this mean 4 will never be supported and instead should use the link provided?
